on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  verify-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get utils
        uses: actions/checkout@v3
        with:
          repository: ASzc/fbc-utils
          ref: main
          path: ./util

      - name: Install Packages
        run: |
          sudo apt install jq skopeo -y
          sudo curl -fLo /usr/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.6/yq_linux_amd64
          sudo chmod +x /usr/bin/yq

      - name: Cache Verified Image Coordinates
        id: cache-coords
        uses: actions/cache@v4
        with:
          path: verified_coordinates
          key: coords1

      - name: Verify Catalog
        env:
          RH_REGISTRY_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME }}
          RH_REGISTRY_PASSWORD: ${{ secrets.RH_REGISTRY_PASSWORD }}
          REGISTRY_AUTH_FILE: /tmp/skopeo-auth
        run: ./util/verify-catalog.sh
